name: Force Update README

on:
    schedule:
        - cron: "*/10 * * * *"
    workflow_dispatch:

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Generate timestamp
              id: timestamp
              run: |
                  echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

            - name: Replace timestamp in README
              run: |
                  sed -i 's/timestamp=[0-9]*/timestamp='${{ env.TIMESTAMP }}'/g' README.md

            - name: Commit & Push
              run: |
                  git config user.name github-actions[bot]
                  git config user.email 41898282+github-actions[bot]@users.noreply.github.com
                  git add README.md
                  git commit -m "timestamp update" || echo "No changes to commit"
                  git push
